### ISSUE TITLE
[stop-note] design standardization considerations

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1868]
- [x] apply standardization to color variables to match the polaris warning / status indicators
 - [x] add `status` to API and support old method
 - [ ] make sure spacing and heading match what the design system calls for
 - [ ] identify icons that are NOT matching the design system

**Comment by btopro** [comment]
right now this looks at icon and goes "this is your status bc of the icon changing" which is a weird key. The API should be more like `<stop-note status="warning">` which `updated` looks at status change and then sets colors via reflected variable and also sets icon automatically because the status changed.

Right now its basically setting the icon, which is reflected, and then using that to throttle what the user sees which is just a bit odd.
