### ISSUE TITLE
[ddd] Design, Develop, Destroy initial starting point

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1869]
- [x] identify first 5 elements for initial design normalization

- [x] - figure-label
- [x] - stop-note
- [x] - learning-component `lrnwebcomponents/elements/course-design/lib/learning-component.js`
- [x] - self-check
- [x] - media-image

- [x] come up with a name for the initiative
- [x] create css / spacing to match the brand
- [x] font usage to match brand
- [x] combine with simple colors so still have access to that pallet
- [ ] identify a color pallet WITHIN simple colors sub-set that is good for visualization (bump it down from 144+ to a reasonable number and reasonable list of colors) https://github.com/elmsln/issues/issues/1833
- [x] start to apply to the different elements 1 at a time starting with #1868

**Comment by cgldevel** [comment]
stope-note refactor consideration: Faculty at Eberly have reported that the stop-note element becomes harder to read in dark mode. See photo for contrast of background and font in dark mode.

<img width="880" alt="Screen Shot 2024-01-08 at 11 28 04 AM" src="https://github.com/elmsln/issues/assets/11019355/07a83a81-efe0-4476-bed9-dea5c3dcb2c8">

**Comment by kchar601** [comment]
![thumbnail_IMG_0730](https://github.com/elmsln/issues/assets/70079563/5e9b9d07-a001-439a-b2c5-9e4e3680e283)

**Comment by btopro** [comment]
![image](https://github.com/elmsln/issues/assets/329735/de1f604f-1042-47e1-8f80-4a82e92a9f6c)

**Comment by kchar601** [comment]
- [x] block-quote

- [ ] table

- [ ] simple-cta

- [ ] accent-card

- [ ] collection-item / collection-list

**Comment by btopro** [comment]
Closing as this has gotten on for awhile and a lot fixed from it. Now new issues associated w/ DDD can be created to solve per element use-cases
