### ISSUE TITLE
Apply DDD to course-intro

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1907]
- [x] spacing on mobile of the icon / sizing
- [x] work on outline spacing to match
- [x] drop the zillion media queries unless we need a few
