### ISSUE TITLE
Add DDD support visually into page-section

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1918]
This is the logical area for 'hero' style content because of what we built for hax.psu as far as it being its own web component

#1917 means that it could pick up and support the same thing but be engineered to visually support DDD

- [x] add support for options for the hero / other named variants. Call this Preset and make it radio option select
- [ ] Try and disable options if a preset is used, but Custom Preset allows for unlocking the options.
- [ ] put all options on the configure tab; custom might need to have them on advanced
- [x] make initial demoSchema stamp down a reasonable one; may actually have reason for multiples here
- [ ] May want to look into demoSchema being able to be used to generate templates in appStore. Could do that with variants / a special flag added to demoSchema based HAXSchema so that it flows to templates area for additional complex variations...

**Comment by btopro** [comment]
![image](https://github.com/elmsln/issues/assets/329735/6dda6657-3d76-419e-bb16-c7593b88b325)

![image](https://github.com/elmsln/issues/assets/329735/31f54f96-758f-4eb2-be22-bb2bde662af5)

![image](https://github.com/elmsln/issues/assets/329735/835bcaf7-7738-4272-bb8c-c9e299d71cc4)

![image](https://github.com/elmsln/issues/assets/329735/ab5b1cb6-be88-4f2b-8e5b-c88e15b21a2f)


![image](https://github.com/elmsln/issues/assets/329735/218d1daa-de42-4e89-a2fd-b1db1dbe6316)
