### ISSUE TITLE
DDD clean up for stabilization in HEAD

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1928]
## blocking
- [x] clean-one font sizing / spacing post-reset
- [x] clean-two font sizing / spacing post-reset
- [x] collection theme
- [x] training theme
- [x] polaris-theme font sizing / spacing post-reset
- [x] polaris-invent-theme font sizing / spacing post-reset
- [x] video players don't respect color if accent set (should...)

- [x] haxor-slevin ( needs some accent card clean up)
- [x] learn-two-theme font sizing / spacing post-reset (menu, side colors need normalized)

## Tier 2
- [x] clean up clean-one dark mode capabilities to ensure they don't conflict w/ DDD
- [x] drop the serif / san-serif option under the text opertaions menu
- [x] see if the text size can be made to work in our new world if mapped to CSS vars correctly

## Tier 3
- [x] video-player styling while on a page-section
- [ ] #1937
- [ ] see spec for trying to render icons in select schema (???)
