### ISSUE TITLE
[haxcms] stop reorganizing the folder structure / page name on move

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#202]
## Tasks for the below
- [x] backend accepts slug
- [x] front end accepts slug
- [x] pathauto applies to new items (even if not on for a decent default)
- [x] user can add new thing with path
- [x] user can bulk add things with pathauto successful

Just make the folder the initial name of the page, maintain that. This is ridiculous that we can't move these around without causing major issues in the structuring of all material. Either we do this or we do a hash that is uuid of the item === content. This is then unchanging. Stop putting everything nested, allow the outline structure to dictate this.

I just saw 4 people now "brick" site content because of restructuring material + the pathauto flag being on (which is always is ootb).

# Pros
- we stop bricking things and its way easier to move
- we can dramatically reduce the logic behind the screens in php and nodejs methods
- site.json has more control over the order of the material (as it does now) and that is a 1-1 with the actual location of material

# Cons
- file system under `pages/` becomes unreadable
- harder to find a piece of content if doing manual debugging
- 100 page site = 100 folders under `pages/`, again, readability issue potentially.

## json-outline-schema
I've extended the spec as written to include `slug`. With slug we should be able to meet our use-case of having a clean looking URL path that's different from the location on the file system. https://github.com/elmsln/json-outline-schema

As we don't build off of the file structure every load (like grav) we should be able to hit a higher scale than grav but we'll worry about that at a later time (for sure).

**Comment by btopro** [comment]
Commits and publishing which initially get at this. Need to do a lot more testing though.
