### ISSUE TITLE
[hax-force] work plan

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#235]
- [ ] publish your element to npm
- [ ] blog on dev.to about what you've learned, what you like about web components, dislike, found easy or difficult, anything in this space. Make sure to reference that your working on these things as part of haxtheweb.

Deeper down the rabbit hole w/ our projects so that you can jump between them more rapidly. Create a space on your computer for git based projects or these projects in general (mine is Documents -> git -> elmsln). Then fork / get these up and running locally:
- [ ] https://github.com/elmsln/lrnwebcomponents This is all of our elements in what's called a mono-repo. Fork the repo and then follow the install directions to get it up and going -- https://github.com/elmsln/lrnwebcomponents#install
- [ ] https://github.com/elmsln/haxcms - git clone this and get it running locally in docker with ddev

With both of the above if you run into issues as far as documentation not making sense or things you had to look up / questions you needed answered in order to get them working, contribute it to this issues queue by filing a new issue: https://github.com/elmsln/issues/issues/new
