### ISSUE TITLE
[hax] btopro priority map

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#401]
- [x] ghosted outline of what you are dragging needs added (timing update screwd it up)
- [x] ensure drag and drop area is clearly defined on drag when in haxcms
- [x] try to replace modal w/ simple-popover for settings and content map (probably just rendering those dedicated elements but in a popover.
- [x] if that works well, find other areas this happens and render those in simple pop over as well (like type conversion)
- [x] add tour directions to other pieces of the UI that are confusing
- [x] #415 improve cursor placement logic
- [x] fix drag / drop targets in grid plates
- [x] drag and drop placement logic not working for new items inserted; could be related to lack of activeNode awareness as far as location relative to other items OR active is being set prior to being added to the page (possible)
- [x] #416
- [x] #410 mobx for hax store state management
- [x] #384 copy paste clean up
- [x] make haxcms leverage the new mobx methodologies (hopefully search and replace)
- [x] check on editMode state integration with HAXcms into HAX
- [x] ensure the "write" system is actually working
- [x] don't position (+) menu between LI elements (show at parent much like grid)
- [x] some autoloader clean up in local testing of HAXcms
- [x] buttons need styles applied on hover
- [x] fix code-editor hax properties not being assigned
- [x] drag and drop image into empty column, needs to know to make and associate to slot
- [x] view source not loading frame
- [x] get rid of paper-dialog
- [x] editMode state between page saves
- [x] buttons out of alignment by 1 px in toolbar
- [x] fix state issue w/ tour when it gets disrupted it can't be reset (tour starts, another menu opened); also when menus open some times the 1st time to activate takes several clicks; probably an initial state issue
- [ ] paste file data from clipboard, needs to trigger an upload as opposed to base64; check for the base 64 decode in the paste operation and see if we can convert this into a file upload workflow use `createObject` from web cam element to achieve this
- [ ] modal to show content not tall enough (default height passed in needs love)
- [ ] open hax, edit something, save, open haxcms menu level and modal content falls behind the background
- [ ] #398 same w/ timing update
- [ ] cut a new release / publish to CDNs
- [ ] grid plate expansion into other things being able to take over the editing experience #348
- [ ] image editor (basic crop / other functions) #397
- [ ] implementing the two of these to form an image gallery #342
- [ ] locking page elements or outline / pages themselves #393
- [ ] #414 web workers for performance in heavy elements like simple-fields
