### ISSUE TITLE
[meta] Removing polymer elements from our lives

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#426]
I've stopped gutting for tonight. all code up in master and in need of A LOT more additional testing before I go anywhere with it. Big deals... no more....
paper-button
paper-fab
icon-icon(s)
lrn-icon
paper-card
paper-icon-button
iron-image
paper-tab(s)
iron-collapse
paper-input
paper-toast
paper-toggle-button
paper-spinner
paper-slider
paper-checkbox

was able to build, spin up in haxcms locally and run through and appear to do everything at a high level. I need to hammer on it more as I'm sure there are some areas where icons are goofy or I missed a class name.

## Big pieces left to remove

haxcms-site-editor haxcms-site-listing are about all this still sits in. Both will improve performance.
- [ ] paper-dialog (shouldn't be terrible)
- [ ] iron-ajax (would be nice to have some equivalent bc of DX, even if it's a class factory)
- [ ] iron-pages (this is another difficult one for sure)

## Places we'll leave them be / review individually
- elmsln- elements
- haxcms polymer base theme elements
- legacy elements we don't use in other elements / might be for specialized apps

**Comment by btopro** [comment]
close enough for this pass. We're probably 90% reduction in polymer elements. HAXcms having very few at this point. We'll get the other ones as we do as this is now fast enough for wider adoption.
