### ISSUE TITLE
[meta] Safari / legacy platform compatibility across the portfolio

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#445]
While difficult to do, we are getting closer to having feature parity between evergreen and Safari / ES5 capable browsers. Safari might benefit from shipping the ES5 builds of things as this has yet to be investigated w/ HAX specifically. Here's some things we KNOW are busted / need some path forward on.

If we test using SeaMonkeys browser (Fork of FF, old....very old..) we can use this as a platform baseline to try and clean up as much functionality as possible. The goal should primarily on getting the OUTPUT to be fine as opposed to the editing experience which we might not be able to support w/ shadowRoot polyfills and `::part` calls. Still, we need to explore this more deeply to see what we can fix.

- [x] polyfill for replaceAll and replaceNode calls
- [x] fix icons in legacy platforms
- [x] modal content is not hidden on initial load (Seamonkeys)
- [x] Tooltips stay present at times if multiple open (Safari 13.0)
- [x] Focus is very jumpy on lines at times as you use the arrowkeys to move through
- [x] text and icon color in the learn two theme are black when they should be white (Safari / Seamonkeys)
- [x] icons go blank after saving a page in HAXcms and going to a new page to start working on (Safari)
- [x] stop doing poor focus logic for left / right keys; try and fix it in Safari or just drop it entirely
- [x] ensure that hitting delete on an "empty" line will get rid of it
- [x] figure out why Safari / FF sometimes lose track of what has focus; if a selection node is found then we should focus that if we somehow are about to lose our focal point. Might have to do w/ the weird BR delete logic.

Let's try and prioritize the output that someone experiences as most Apple based browser traffic is iphone for our audiences. I have still yet to meet a developer that uses Safari daily and I hope to not. Safari is the new IE11 as far as our platform is concerned as it constantly cripples the web API capabilities to force developers to ship apps through its app store. It is a profiteering based browser, and why Edge and Chrome have their data stealing desires and universal tracking, they at least build out the web to the fullest. Firefox stands alone, fortunately up to webcomponents capabilities as of late 2019 (in ESR even) so that we can depend on it to ship sites fast, untracked, and in alignment with the vision of the web as everyone's platform without compromise.

Rant aside, let's do a deep dive on browser compliance w/ HAX and HAXcms. While we do have other elements, these two are the biggest by far and will ensure we cover the most used APIs so we know the browser works best with all our assets. Let's test these deeply and ensure again that we have sign off on their working in all areas
- [x] Chrome (primary dev platform)
- [x] Edge (same as chrome + tested)
- [x] Opera (same as chrome + tested)
- [x] Firefox
    - [x] can't see cursor in a contenteditable area as to where you are typing
    - [x] text of menu not visible
    - [x] some focus issues while typing
    - [x] font size is jacked up in learn two at minimum
- [x] Beaker
- [x] Brave
- [x] Safari
  - [x] 9.1 (with conditions, at least loads)
  - [x] 10.1 (with conditions, output only)
  - [x] 11.1 (with conditions, output only)
  - [x] 12.1 (with conditions, output only)
  - [x] 13.1 (all functionality)
  - [x] 14.x (when released widely)
- [x] Seamonkeys (with conditions)
