### ISSUE TITLE
[meta] developer tag that renders a hex code + color picker to change (as option)

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#534]
I saw a feature in slack where if you type a hex code it shows you the color like so:
![image](https://user-images.githubusercontent.com/329735/107839984-402d9200-6d7d-11eb-9d1f-27577b7188d3.png)

It would be really cool to have a webcomponent that does this. Input is a hex code and then it displays the color as a small box. Could also support 8 digit for opacity. Addtionally if put in an "edit" mode of some kind then it could be ac ool color picker where you can change the color via a widget, bound to the prop so that it displays this.

Limited utility directly but a cool demo of functionality and also be a gateway to tools like this https://color.adobe.com/create/color-wheel

**Comment by btopro** [comment]
#540

**Comment by btopro** [comment]
@collinkleest reviewed PR; looking slick. immediate things
- [ ] make opacity start at fully visible. This is confusing from a null case. Could easily FORCE things to be FFFFFFFF out of the gate
- [ ] ensure no more than 8 chars are entered. I see your trapping keys which is awesome; just make sure it can't be 50 chars long :)
- [ ] update each slider as each 2 chars are typed; or at least ensure that matches for 3 char, 4 char, 6 char, and 8 char lengths are accounted for. Right now there's only 8 char that updates the sliders
