### ISSUE TITLE
[meta] play w/ idea of tag field from a predefined list

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#572]
- [x] use <simple-fields-tag-list></simple-fields-tag-list> as a starting point and add things into it
- [x] feed this other tag an array of possible tags
- [x] user clicks these tags (color + label, alphabetical)
- [x] tag shows up in our simple-tags-field style input
- [x] option for requiring the input to be from this list (so can't do custom tag typing)
- [x] need a new tag for the grouping / visualizing predefined list
- [x] then need a minor data structure for passing into this (color + title + array of labels)
- [x] Take the click event off of these tags and use that to change state to imply selected; also keep track of whats selected in this grouping element. Ensure that it has little CSS styling and parts to mod as needed.
- [x] Support for pulling list from an end point as another element which takes a list of categories + data for each and then renders it. This would support the example shown in the mock up below.
- [x] tag-rubric element that has areas of focus (like Good, Needs Work, Terrible, etc) and the ability to then place the tags in each bucket. This could work w/ grid plate for drag and drop of tag elements into the appropriate space potentially

This would allow #571 to allow for faculty and students to have a system driven series of tags so that they could give each other feedback (or faculty) BUT its within system driven parameters. Meaningful feedback (like pick 3 things that worked well, 3 things 
that could be improved, and 5 statements that characterize this work) and the color coding is relative to positive, needs improvement, and flavoring if you will.

**Comment by michael-collins** [comment]
Having categories of tags, while it’s okay if it’s too complex, would be great. If I need to give feedback on typography I can select from all the tags that are tagged with the category of typography, or graphic design, or visual elements. This would help with find-ability when we have a 1000 tags in the system and would make them easily browsable if the instructor forgets what the terms is called, but knows it's related to a particular category of items.

<img width="493" alt="Screen Shot 2021-03-05 at 4 25 48 PM" src="https://user-images.githubusercontent.com/1085304/110175267-7f289380-7dcf-11eb-826b-028bf934d649.png">

**Comment by michael-collins** [comment]
@nikkimk Maybe something like this to start?

![Studio 3 0](https://user-images.githubusercontent.com/1085304/110220434-c5dfc180-7e93-11eb-824e-f282e2b33847.png)

**Comment by michael-collins** [comment]
@btopro How do we maintain these tags, their categories, their definitions, and links to external content ( IE youtube tutorials)? Could we do importing and exporting of CSV files? This way all the faculty could contribute, and we could all have access to the same tag base as a google spreadsheet for instance.

**Comment by btopro** [comment]
This sounds like a lot of maintenance / management for a tagging system. CSV or something like it ya probably. Links to things break or go out of doubt so not a huge fan of that level of data maintenance. We'd have to agree on a data structure for this "tag" though in either regard. My current thought was entry would be via a field where you type and hit enter and it generates tags off of all the data entered there. If we're starting to get into full content modeling off of each word that complicates that type of input / management so you might need to give me a data model for what you are describing as "a tag" as my reading of above was that it's a word and can be placed into a category (color coded) and then when applied is under a rubric category of sorts as far as how that word is applied to the idea.

In this model there is no real association beyond a word has a word association (Kerning -> Typography) and then when I apply Kerning to the "Needs improvement" area that's just data being put in array position 1 instead of 2 sorta thing. If we start going Kerning has this youtube video, we're discussing kerning as a much more complex piece of data potentially.

So what are all the data thoughts here

**Comment by michael-collins** [comment]
I was already compiling one. The tags alone will probably breed a lot of emails because it's essentially just a word if it's not interactive. If they were able to click on the word, Kerning, then read the definition, then go to a video about that process, we could go from marginal improvement in learning to "here's everything you need to know, don't send your instructors a ton of emails about where to learn kerning". I understand regarding the data model aspect. I imagined it like, oh, column 1 array has these words. Let's create a button from this jason file, find that word, add in any definitions and links it might have. Then pop up some options when the button is hovered over.

**Comment by michael-collins** [comment]
Okay, I've officially stopped re-editing that comment box now.

**Comment by btopro** [comment]
I wonder if we couldn't use a field for uploading a CSV as we have things for downloading CSV table data. Then we could use editable-table and other tags we have for editing and visualizing directly in an edit view. This could allow for uploading a file drag and drop for the starting point, or downloading what's there to work on in tool of choice. But then, ultimately it's saved in page and goes to the backend as a json / csv file.

I'd have to think on this some more but if we knew what the fields were and this could just be treated like a big excel document sitting in the page that might help. I seem to recall at one point you showing me some kind of JSON editor in browser as "configuration". I wonder if we take the editable-table component and weaponize it in this way; just saving lots of small configuration files as json blobs but allowing user to edit the values (tags being 1 of them). Another obvious option (in my mind) is if students can generate new tags, use existing, or only have the comment box (this came up in meeting today).

**Comment by michael-collins** [comment]
I think a table editor would be a good way to handle/visualize it. Here is an example filled out for kerning. I have linked to a Kerning practice website, and a video explanation of kerning: https://docs.google.com/spreadsheets/d/19iOjjnn3zAhmgat-mIfF8zAxsfceiodDalftLqBWaTk/edit?usp=sharing

**Comment by michael-collins** [comment]
User generated tags could be interesting, but they can also just free form type anything that they don't have available to them, so it's not a major concern that they add to the bank of tags at this point in my opinion.

**Comment by btopro** [comment]
is the comma in each category a different category? Like the term is tagged into multiple taxonomies potentially?

**Comment by michael-collins** [comment]
Correct.

**Comment by btopro** [comment]
I'd see these as like term, categories, description, and then either a required link to more info some place external or a open field for entering anything, and this just happens to have a link. Which do you think would be better? Cause I could see maybe wanting to link to multiple resources.

Non-art example (but generic to fit)
- Term: Web component
- Categories: Front end, Web development, Web standards
- Description: A meta-specification that allows for deploying new components in a cross browser compliant manner without additional code libraries.
- MoreInfo: 4 common links for more details OR should this maybe be like categories where comma separated list of links and then made into visually a list of links for more info?

Just trying to think through flexibility here on that last field; the other 3 work as is.

**Comment by michael-collins** [comment]
First three look good.

If this is in a learning context, a learning related term would be good. If it's a more general tool, then a non-edu term should probably be used. I'm in favor of edu terms for this at this point.

OER Schema has some terminology we can use, "associated material" or "supporting material":

I used the last field as 'associated material' because it's essentially anything associated to the term in a learning context, though now that I look at it, "supporting material" may be better suited: http://oerschema.org/docs/schema.html

If it's merely a list of comma separated values, you could do what google sheets did, and generate title and links from the links themselves if the metadata exists, see screenshot from a few comments ago. We could also just have a more info link and go to a sort of home on the web for that particular item, though we'd have to build that somewhere. I think the associated material column allows you to decide if you want to go to an informational type of page on the web, or to put in individual links, so it might not be mutually exclusive.

**Comment by btopro** [comment]
gotcha; I mean 1 resource could also be associated with whatever terms you want. What could be injected as schema and potentially used as a glossary of terms and technique in the course? Thinking in those terms might help us to then just make multiple schema / meta tag associations in the content and align goals w/ oerschema (like this idea).

**Comment by michael-collins** [comment]
Yeah, that makes sense to me.

**Comment by btopro** [comment]
Consolidating to #574 and then probably a dedicated grade-book issue from there as a lot of these ideas are already in the prototype :) Will keep evolving this
