### ISSUE TITLE
[meta] stand alone rubric tool

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#574]
Need to dust this off again now that we have vercel and the microservices stuff figured out. Could be good for PDF generation / workflows that subvert solutions and more so enhance workflows.
Taking #572 we could EASILY do the following:
- [x] Google Docs backend that has the correct structure
- [x] make a UI that makes tags
- [x] as tags added, build a feedback tab that illustrates what feedback is being generated for the user based on used tags (read off the description and the more info props)
- [x] click the tags to build our feedback / drag and drop into categories of a rubric
- [x] add support for showing the full text + additional resources as a "print" mode of sorts
- [x] place work in 1 window, this UI in the other (https://blog.bitsrc.io/4-ways-to-communicate-across-browser-tabs-in-realtime-e4f5f6cbedca breakdown of how to do this)
- [x] look into a split pane / toolbar for moving between works / seeing stats and picking new students to review
- [x] Split pane is work on left, rubric on right
- [ ] Consolidate rubric tabs into left to right eval which shows the score awarded / if it's been done for at the faculty level via a color coding system
- [x] Tags need to live some place that's easy to apply them like currently.
- [x] Also might want to think about a two window / dual monitor approach. In Dual monitor mode another window is popped up from parent but HAS full data messaging access via PostMessage. The 2nd window is just the player of student work. This gives more room for the rubric engine
- [x] Make sure can toggle to full gradebook display without it needing to reload entire interface
- [ ] store values in local storage / ensure there's a confirm to reload sorta thing going on
- [ ] click "generate textual feedback" and dump it to a written form or even print mode

This would EASILY allow for evaluating other things while hooking up a dynamic bank of grading from google docs. The instructor is augmented to improve their workflow, and empowered to remix how it operates. They can then use the tool in a platform agnostic way so that they can augment legacy edtech corporations like Cantvas and WhiteBoard.

**Comment by michael-collins** [comment]
If we can attach points to the rubric as well, that would be super helpful. I feel like entering in a grade during this process is the logical next step

**Comment by btopro** [comment]
@michael-collins can you describe how points are attached? It looks like you have a very qualitative rubric of "great" or "needs improvement" which doesn't directly lend itself to pts. Do you just assign a score or do you have a rigid criteria for this being the case?

**Comment by michael-collins** [comment]
### Exercise rubric

<img width="584" alt="Screen Shot 2021-03-10 at 9 36 44 AM" src="https://user-images.githubusercontent.com/1085304/110645842-52d09680-8184-11eb-8624-7e251bc566ad.png">

### Project Rubric

<img width="535" alt="Screen Shot 2021-03-10 at 9 38 32 AM" src="https://user-images.githubusercontent.com/1085304/110645983-74ca1900-8184-11eb-8714-e33d6609603f.png">

**Comment by btopro** [comment]
So would tags get dragged into this as well? Or would there be the qualitative columns under EACH of these criteria + free form area, at which point a 18% is highly subjectively handed but you are applying tags as you go through and then go "hmm... like 4 things they did right, but 8 of these other things are totally missing... I'll give that 12/20". Trying to establish if it's qualitative with a field for entering a score as opposed to tags / rubric usage having some mathematical association to points / %s.

All our past rubric designs were a mix of these but always had like levels of quality as the "qualitative" areas. This was EXTREMELY intensive on setup and didn't scale (Art 20 did this in its rewrite of the rubric tool they used offline). I like the idea of what you have above + the tagging dropped into a level of quality and then you as grader actually just make up a value to match what you think that's worth as a result. That reduces complexity in the app and keeps the focus on speeding up assessment as opposed to automating it completely rigidly.

**Comment by michael-collins** [comment]
Yes, dragging tags into each criteria would be great (in the two or three categories). I write it in manually at the moment. I wouldn't apply math directly to tags, they don't correspond, or at least not how I do it. I use my judgement of, "this is an A, or this is a B". The tags help to justify the associated grade.

If there was a way to do this automatically, that would be great, I'm open to ideas. Configuring values in some way for tags would be cool.

**Comment by btopro** [comment]
I'll start w/ configuring tags and combining what you have above here w/ the tagging quantification method. End of the row I could put a ____ / 20pts sorta thing and you fill in the blank. Do you think adding support for grading scale would be useful too? Like as you enter values I could compare and put a big letter A- or whatever to help reinforce what the evaluation relates to? Also could help w/ color coding / seeing all grades at a high level to know "wow I gave out like 50% Cs on this, better cover this deeper" sorta thing.

**Comment by michael-collins** [comment]
Yeah, those additions would be nice to have, would parity what other grading tools do. That can be an additional sheet I think.

**Comment by btopro** [comment]
#1265

**Comment by btopro** [comment]
https://haxapi.vercel.app/?path=/story/education-tag-grader--grade-book-lite-story
