### ISSUE TITLE
[grade-book] Task list

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#585]
- [x] see if editable-table-display will work nicely w/ the `data` property (map'ing template stamp approach isnt cutting it) otherwise let's just replicate it's styles and make a new table editor thats specific (unfortunately)
- [x] click on an assignment + student cross section to activate it in other tab
- [x] make sure gradebook has scroll into view on active change. This way the gradebook its easier to pan in all directions to what's active
- [x] sticky the initial columns that are for student info
- [x] hover highlight what you are going to activate in the display
- [x] create a gradebook-store
- [x] active indicator in top bar that shows active assignment and active student
- [x] dropdown menu that shows students by photo - name
- [x] ability to collapse the controls away into top bar
- [x] Ability to adjust column sizes / grading view
- [x] submission map smaller, less jarring (purely for reference)
- [x] singleton so only 1 grade book on page
- [x] ask nikki how to post it to the storybook
- [x] dark mode working
- [x] Student report should read "Student report view" and is a button that opens it in a modal.
- [x] open gradebook table in a tab as default, start making review work a mode 
- [x] look into letter-grade spacing on text at small and large sizes
- [x] Assessment view in one panel (right), submission in the other (left)
- [x] #693 so we have a workflow for editing overall / pure CSV / Excel style editor
- [x] ensure opened window for expand mode is not 100% but still tall
- [x] conditionally render the col-3 based on displayMode being `2`
- [x] make sure events emit off of the grade input
- [x] load the initial file system reference using a worker (maybe this happens in the file system singleton itself)
- [x] store a reference to the previously selected file and then offer that as the one to load via a single button push
- [x] only show file system option if platform supports it (disabled and saying to use Chrome/Edge/Opera if so)
- [x] see why responsive utility is mad opening data in another window
- [x] get state management figured out for activeSubmission so we can open in new window
- [x] remove the number input from the table
- [x] add a point value / total arrow indicator that slides up to point to how many points they are assigning per category and where that lands PER rubric category
- [x] Add to click event on the grade slider so that it just sets the value to the highest possible value for that letter grade
- [x] visualize the point totals suggested per letter grade
- [ ] move grade to top right corner w/ overall points so we can sticky it on long scroll
- [ ] move the open in new window button to the tool bar in the pop up mode
- [ ] padding around the iframe / submission in the modal
- [ ] add the mirroring grade value by adding the letter grade visual / updater in the tool bar in the pop up too
- [ ] ensure state is accurate for activeSubmission triggering the popup to change
- [ ] ensure point values for new rubrics to be worked on are wiped, pause, THEN put back on page to avoid data value stickying
- [ ] Move the input for score into the grade slider so that we can query directly from it / remap events to something less poluted (value-changed is far too generic overall)
- [ ] create a activeSubmissionScore which stores the values / sets them back into the associated datbase part when moving to a new assignment. This is the bridge between creating score values and us having the raw data that we need to set in the json blob later on.
- [ ] ability to manually switch viewer of how the assignment is presented. In case we goof up in our detection or they have a specific way to view it.
- [ ] for relational data, just output a json blob so that we can easily do the qualitative + quantitative in an easy manner. This will limit to a production backend or local file system but that's fine so long as we can recall it and write back to it.
- [ ] make an lms sheet which is computed and used as a look up. this can drive initial setup OR be computed for import
- [ ] ooooo what if studio is passthrough to initially populate this as well
- [ ] then sis / student id info from canvas is the pk across other parts for the user
- [ ] populate the associated point value to the right of the letter-grade-picker input
- [ ] mode for editing the raw grid of score values
- [ ] load dataset off elmsln format for studio backend (allow toggling format)
- [ ] search by name / email
- [ ] assignment dropdown by name, due date shown
- [ ] Modal then has ability to print or download as image (grab canvas element, inject link then click for auto download)
- [ ] ability to hit control and click to select multiple, which then shows multiple selected there
- [ ] Changing student or assignment sets the values back into the "database"
- [ ] Button to download current database / xlsx
- [ ] Use https://web.dev/browser-fs-access/ so we can support Safari / FF with better support for local file system ops even if not perfect
