### ISSUE TITLE
[meta] btopro priority task map

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#604]
continuing from #401 which was a very successful methodology the next tasks are..
- [x] ensure that hitting delete on an "empty" line will get rid of it; Safari / FF glitchy here at times
- [x] figure out why Safari / FF sometimes lose track of what has focus even if just for a moment (might be more hidden br / span)
- [x] make the heading hierarchy that's like the menu but simplified
- [x] implementing the two of these to form an image gallery #342
- [x] [simple-icon-picker] performance slog #601
- [x] #600
- [x] work on voice system so it can be a weird demo in class (make sure it still works)
- [x] #610
- [x] #588
- [x] #573
- [x] #625
- [x] #591
- [x] #627 
- [x] #626 
- [x] #621
- [x] #633
- [x] #635
- [x] #634
- [x] #622
- [x] #614
- [x] #605
- [x] #606
- [x] #506
- [x] #636
- [x] #623
- [x] #285
- [x] wire up simple-autocomplete to list of possible tags while typing
- [x] group the items in the add menu by a primary grouping / type visually
- [x] #446 rope in the rich text editor as an advanced option
- [x] #485
- [ ] #505
- [ ] #574
- [ ] #824
- [ ] #825
- [ ] #826
- [ ] #827
