### ISSUE TITLE
[meta] build a code pipeline / documented process for contributing to doc sites

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#644]
We need a pipeline / devops workflow for building out a documentation / automated code pipeline for rebuilding hax11ty sites to communicate about the many projects we have. We need a similar contribution workflow and structure for..
- [x] hax11ty (the project itself)
- [x] wcfactory.js.org
- [ ] haxtheweb.org
- [ ] haxcms
- [ ] elmsln.org
- [ ] https://github.com/elmsln/documentation with hax11try

## Steps to replacing / updating these sites
- check out existing site if in version control / repo based; if new, use hax11ty as a template to start it
  - replace page paths from `foldername/index.html` to `foldername.md` so that it's the name of a file
- add yaml for title to the page (even tho its not md this doesnt matter)
```yaml
---
title: About
---
```
- copy the files folder over
- ensure the CNAME file is there
- ensure the dist directory is there but empty with just [dot] files in place
- update the settings.js file as nessecary, though most should "just work"

**Comment by whatsacomputertho** [comment]
Will look into it

**Comment by btopro** [comment]
@whatsacomputertho consider it assigned and thank you. summarizing a tangible output:
- wcfactory uses haxcms to deliver its content
- ideally it would use hax11ty which allows for github actions, static site integrated workflows
- wcfactory is a less critical repo so if we have to mess with it around the time of switching, unicorns wont cry
https://github.com/elmsln/wcfactory.js.org repo
https://wcfactory.js.org/ website running off `gh-pages`

Look into hax11ty and how it builds content; look at the content of wcfactory.js.org. Ask questions in order to align the content of the repo w/ the tooling approach of hax11ty.

If we can get a process for doing this with 1 site, then we'll be able to do it with any of our other properties more easily or other people can get it as work in order to dig into the weeds of them and learn all aspects as well.

**Comment by whatsacomputertho** [comment]
**Status Update**
- Looked into some elmsln content discussing HAX integration into 11ty
- Simulated contribution to a documentation site by creating a pull request
- In general, a bit confused on the requirements of this issue, see my message on slack
