### ISSUE TITLE
[meta] make a csv editor w. Local file api and editable-table

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#693]
- [x] Forces me to make a editable-table csv loader from local demo
- [x] Make it as stand alone and then abstract a Singleton for working with file system
- [x] Load up a potential "grade book" data set in grade-book using this approach to start everything off
