### ISSUE TITLE
[studio] task list for next studio integration

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#700]
setup studio at `dowhatever` play space we use. Then get it wired in to work there (while the old studio still is completely able to run in parallel as / if needed):

- [x] copy and rename current v2 studio to v3. The whole APIs and everything as well so we can run both. No need to make an install profile this times will adjust studio default when finished
- [x] make the new output for the webcomponent to power it actually load in the right place 
- [x] get sftp env setup and do this on a fake studio space 
- [x] look at how routing had to account for this in studio locally as far as how the old one did
- [x] support wiring in the fake data so we can analyze making it come from real data one endpoint at a time
- [x] hide UI / set base for the top menu items as new studio takes over for these
- [ ] Leverage our internal helper classes to transform the drupal studio data into what the new studio is looking for
- [ ] Overload class for our purposes in the 2021 version of the API or take the output of the current one as a basis for forming the API needs in elmsln-studio
- [ ] think up how the gradebook assignment workflow can power the data for the drupal based setup 
- [ ] use current studio editing UI to generate dummy content for the space rapidly so we can work with the API to make it match needs

**Comment by btopro** [comment]
needs to be done via microservice approaches being explored currently
